# Generated by Django 2.2.8 on 2019-12-13 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0003_auto_20191213_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscriber',
            field=models.ManyToManyField(blank=True, related_name='sub_cat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
